### ISSUE TITLE
custom api must translate to db GET call

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/helpers#3]
Tentative algorithm:
- transform long url to dict
- exit with error if url not valid
- get varname (VARNAME_unit):
   - if rate is specified, concat name and rate
   - else pick default nominal unit (from where?)
   - if agg is specified - get dataset and perform transform (how?)
- from if start year or end year is specified, translate this to start_date and end_date
- make call to db GET method

Specs at <https://github.com/mini-kep/intro/blob/master/specification/custom_api.md>

**Comment by epogrebnyak** [comment]
QUESTION: the original intent was to provide user with no-parameter import
soultion like pd.read_json('<long url>'), this does not seem to be able to work
    
Options: 
 1. ```pd.import_json('<long url>', orient='split')```
 2. ```pd.read_csv('<long url>', converters={0: pd.to_datetime}, index_col=0)```
    
I slightly favour 2) because this way we will have one format less in general, even
though it is slightly longer on client side. What is your opinion?

**Comment by Perevedko** [comment]
the difference is small, but if we use CSV in other parts of application, i think we should prefer it

**Comment by epogrebnyak** [comment]
Follow up:
- @SuperVasya: integrate csv serialiser to database layer + update [db specification](https://github.com/mini-kep/intro/blob/master/specification/database.md) accordingly.
- @relique - can we integrate CustomGET class to frontend app? I'm not sure about error handling, need to discuss
- @zarak - as an English speaker, can you draft [custom api specifiaction](https://github.com/mini-kep/intro/blob/master/specification/custom_api.md) based on module docstring and implementation at [custom_api.py](https://github.com/mini-kep/helpers/blob/master/custom_api.py)?
- @Perevedko - are you willing to do unit testing of  [custom_api.py](https://github.com/mini-kep/helpers/blob/master/custom_api.py)?

**Comment by epogrebnyak** [comment]
As for error handling can use: <http://flask.pocoo.org/docs/0.12/patterns/apierrors/>

**Comment by zarak** [comment]
Ideally the user can use `pd.read_csv` without having to specify any parameters other than the url, but maybe it's not such a big issue as one can easily wrap the function call in a partial:
```python
from functools import partial
read_csv = partial(pd.read_csv, converters={0: pd.to_datetime}, index_col=0)
```

**Comment by epogrebnyak** [comment]
Thanks for ```partial``` - never knew about it, seems like a clean way to abstract from parameters. 

From <https://docs.python.org/3.6/library/functools.html#functools.partial> looks like the strength of partial is to allow the additional parameters to be called if necessary.

**Comment by epogrebnyak** [comment]
The ```CustomGET``` class at 
<https://github.com/mini-kep/helpers/blob/master/custom_api/custom_api.py> seems a bit mroe stable now, really want to mount it:
- [ ] at [frontend](https://github.com/mini-kep/frontend-app/blob/master/apps/views/time_series.py) with @relique 
- [ ] at db repo with @SuperVasya
